### ISSUE TITLE
Invalid txn fee when trying to register an hotspot without assert location

### ISSUE THREAD

**Issue by dannpl** [helium/maker-starter-app#41]
"failed_reason": "{invalid,wrong_txn_fee}",

He have my request for this hotspot. so I was successful when sending the location
`https://api.helium.io/v1/accounts/14LRiBNfxfdvWNULoXQzPYewHLfZdcZwPJTkDWLbZgZDA1BZpHN/pending_transactions`
`https://api.helium.io/v1/pending_transactions/qeqkvOjTbsaz3i-RPQN2w42B4jN5qJiS65VGiZeAlIQ`

The first object was the response successfully after registering with location.
The last and oldest was without location
![Screen_Shot_2022-05-25_at_17 14 21](https://user-images.githubusercontent.com/37663993/170400989-ee81e1ae-ca0c-4a15-b1dc-2bfabccabd84.png)

**Comment by cokes518** [comment]
usually when `staking_fee: 1` it means the Hotspot has not synced enough of the chain to figure out what the fee should be and/or there was a network outage.

since you filed this issue yesterday, and we know there was an outage, it's likely the root cause. recommend you try again and open a new issue if it's still happening.
